#!/bin/sh

export APP_PROD_ENV='TRUE'
export APP_DATABASE_NAME=$APP_DB_NAME
export APP_DATABASE_USER=$APP_DB_USERNAME
export APP_DATABASE_PASSWORD=$APP_DB_PASSWORD
export APP_DATABASE_PORT=$APP_DB_PORT
export APP_DATABASE_HOST=$APP_DB_HOST
export DJANGO_SECRET_KEY=$APP_SECRET_KEY
gunicorn nerd_agile_cli_project.wsgi:application
